 const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS";
 const GET_IMAGES_FAILURE = "GET_IMAGES_FAILURE";
 const GET_IMAGES_LOADING = "GET_IMAGES_LOADING";

 export { GET_IMAGES_SUCCESS,GET_IMAGES_FAILURE,GET_IMAGES_LOADING };